import gluestackPlugin from "@gluestack-ui/nativewind-utils/tailwind-plugin";

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "media",
  content: ["app/**/*.{tsx,jsx,ts,js}", "components/**/*.{tsx,jsx,ts,js}"],
  presets: [require("nativewind/preset")],
  safelist: [
    {
      pattern:
        /(bg|border|text|stroke|fill)-(primary|secondary|tertiary|error|success|warning|info|typography|outline|background|indicator)-(0|50|100|200|300|400|500|600|700|800|900|950|white|gray|black|error|warning|muted|success|info|light|dark|primary)/,
    },
  ],
  theme: {
    spacing: {
      0: "var(--spacing-0)",
      1: "var(--spacing-1)",
      2: "var(--spacing-2)",
      3: "var(--spacing-3)",
      4: "var(--spacing-4)",
      5: "var(--spacing-5)",
      6: "var(--spacing-6)",
      7: "var(--spacing-7)",
      8: "var(--spacing-8)",
      9: "var(--spacing-9)",
      10: "var(--spacing-10)",
      11: "var(--spacing-11)",
      12: "var(--spacing-12)",
      14: "var(--spacing-14)",
      16: "var(--spacing-16)",
      20: "var(--spacing-20)",
      24: "var(--spacing-24)",
      28: "var(--spacing-28)",
      32: "var(--spacing-32)",
      36: "var(--spacing-36)",
      40: "var(--spacing-40)",
      44: "var(--spacing-44)",
      48: "var(--spacing-48)",
      52: "var(--spacing-52)",
      56: "var(--spacing-56)",
      60: "var(--spacing-60)",
      64: "var(--spacing-64)",
      72: "var(--spacing-72)",
      80: "var(--spacing-80)",
      96: "var(--spacing-96)",
      "v-0": "var(--v-spacing-0)",
      "v-1": "var(--v-spacing-1)",
      "v-2": "var(--v-spacing-2)",
      "v-3": "var(--v-spacing-3)",
      "v-4": "var(--v-spacing-4)",
      "v-5": "var(--v-spacing-5)",
      "v-6": "var(--v-spacing-6)",
      "v-7": "var(--v-spacing-7)",
      "v-8": "var(--v-spacing-8)",
      "v-9": "var(--v-spacing-9)",
      "v-10": "var(--v-spacing-10)",
      "v-11": "var(--v-spacing-11)",
      "v-12": "var(--v-spacing-12)",
      "v-14": "var(--v-spacing-14)",
      "v-16": "var(--v-spacing-16)",
      "v-20": "var(--v-spacing-20)",
      "v-22": "var(--v-spacing-22)",
      "v-24": "var(--v-spacing-24)",
      "v-28": "var(--v-spacing-28)",
      "v-32": "var(--v-spacing-32)",
      "v-36": "var(--v-spacing-36)",
      "v-40": "var(--v-spacing-40)",
      "v-44": "var(--v-spacing-44)",
      "v-48": "var(--v-spacing-48)",
      "v-52": "var(--v-spacing-52)",
      "v-56": "var(--v-spacing-56)",
      "v-60": "var(--v-spacing-60)",
      "v-64": "var(--v-spacing-64)",
      "v-72": "var(--v-spacing-72)",
      "v-80": "var(--v-spacing-80)",
      "v-96": "var(--v-spacing-96)",

    },
    // borderWidth: {
    //   xs: "var(--border-width-xs)",
    //   sm: "var(--border-width-sm)",
    //   base: "var(--border-width-base)",
    //   lg: "var(--border-width-lg)",
    //   xl: "var(--border-width-xl)",
    //   "2xl": "var(--border-width-2xl)",
    //   "3xl": "var(--border-width-3xl)",
    //   "4xl": "var(--border-width-4xl)",
    //   "5xl": "var(--border-width-5xl)",
    // },
    // borderRadius: {
    //   xs: "var(--border-radius-xs)",
    //   sm: "var(--border-radius-sm)",
    //   base: "var(--border-radius-base)",
    //   lg: "var(--border-radius-lg)",
    //   xl: "var(--border-radius-xl)",
    //   "2xl": "var(--border-radius-2xl)",
    //   "3xl": "var(--border-radius-3xl)",
    //   full: "var(--border-radius-full)",
    // },

    extend: {
      colors: {
        width: {
          0: "var(--fs-lh)",
          mv: "28px",
        },
        spacing: {
          0: "var(--spacing)",
          md: "30px",
        },

        screens: {
          xs: "380px",
          sm: "620px",
          md: "768px",
          lg: "1024px",
          xl: "1280px",
          "2xl": "1536px",
          mm: "500px",
        },
        primary: {
          0: "rgb(var(--color-primary-0)/<alpha-value>)",
          50: "rgb(var(--color-primary-50)/<alpha-value>)",
          100: "rgb(var(--color-primary-100)/<alpha-value>)",
          200: "rgb(var(--color-primary-200)/<alpha-value>)",
          300: "rgb(var(--color-primary-300)/<alpha-value>)",
          400: "rgb(var(--color-primary-400)/<alpha-value>)",
          500: "rgb(var(--color-primary-500)/<alpha-value>)",
          600: "rgb(var(--color-primary-600)/<alpha-value>)",
          700: "rgb(var(--color-primary-700)/<alpha-value>)",
          800: "rgb(var(--color-primary-800)/<alpha-value>)",
          900: "rgb(var(--color-primary-900)/<alpha-value>)",
          950: "rgb(var(--color-primary-950)/<alpha-value>)",
          c: "rgb(var(--color-c-primary)/<alpha-value>)",
          c_light: "rgb(var(--color-c-primary-light)/<alpha-value>)",
        },
        secondary: {
          0: "rgb(var(--color-secondary-0)/<alpha-value>)",
          50: "rgb(var(--color-secondary-50)/<alpha-value>)",
          100: "rgb(var(--color-secondary-100)/<alpha-value>)",
          200: "rgb(var(--color-secondary-200)/<alpha-value>)",
          300: "rgb(var(--color-secondary-300)/<alpha-value>)",
          400: "rgb(var(--color-secondary-400)/<alpha-value>)",
          500: "rgb(var(--color-secondary-500)/<alpha-value>)",
          600: "rgb(var(--color-secondary-600)/<alpha-value>)",
          700: "rgb(var(--color-secondary-700)/<alpha-value>)",
          800: "rgb(var(--color-secondary-800)/<alpha-value>)",
          900: "rgb(var(--color-secondary-900)/<alpha-value>)",
          950: "rgb(var(--color-secondary-950)/<alpha-value>)",
          c: "rgb(var(--color-c-secondary)/<alpha-value>)",
        },
        tertiary: {
          50: "rgb(var(--color-tertiary-50)/<alpha-value>)",
          100: "rgb(var(--color-tertiary-100)/<alpha-value>)",
          200: "rgb(var(--color-tertiary-200)/<alpha-value>)",
          300: "rgb(var(--color-tertiary-300)/<alpha-value>)",
          400: "rgb(var(--color-tertiary-400)/<alpha-value>)",
          500: "rgb(var(--color-tertiary-500)/<alpha-value>)",
          600: "rgb(var(--color-tertiary-600)/<alpha-value>)",
          700: "rgb(var(--color-tertiary-700)/<alpha-value>)",
          800: "rgb(var(--color-tertiary-800)/<alpha-value>)",
          900: "rgb(var(--color-tertiary-900)/<alpha-value>)",
          950: "rgb(var(--color-tertiary-950)/<alpha-value>)",
        },
        error: {
          0: "rgb(var(--color-error-0)/<alpha-value>)",
          50: "rgb(var(--color-error-50)/<alpha-value>)",
          100: "rgb(var(--color-error-100)/<alpha-value>)",
          200: "rgb(var(--color-error-200)/<alpha-value>)",
          300: "rgb(var(--color-error-300)/<alpha-value>)",
          400: "rgb(var(--color-error-400)/<alpha-value>)",
          500: "rgb(var(--color-error-500)/<alpha-value>)",
          600: "rgb(var(--color-error-600)/<alpha-value>)",
          700: "rgb(var(--color-error-700)/<alpha-value>)",
          800: "rgb(var(--color-error-800)/<alpha-value>)",
          900: "rgb(var(--color-error-900)/<alpha-value>)",
          950: "rgb(var(--color-error-950)/<alpha-value>)",
        },
        success: {
          0: "rgb(var(--color-success-0)/<alpha-value>)",
          50: "rgb(var(--color-success-50)/<alpha-value>)",
          100: "rgb(var(--color-success-100)/<alpha-value>)",
          200: "rgb(var(--color-success-200)/<alpha-value>)",
          300: "rgb(var(--color-success-300)/<alpha-value>)",
          400: "rgb(var(--color-success-400)/<alpha-value>)",
          500: "rgb(var(--color-success-500)/<alpha-value>)",
          600: "rgb(var(--color-success-600)/<alpha-value>)",
          700: "rgb(var(--color-success-700)/<alpha-value>)",
          800: "rgb(var(--color-success-800)/<alpha-value>)",
          900: "rgb(var(--color-success-900)/<alpha-value>)",
          950: "rgb(var(--color-success-950)/<alpha-value>)",
        },
        warning: {
          0: "rgb(var(--color-warning-0)/<alpha-value>)",
          50: "rgb(var(--color-warning-50)/<alpha-value>)",
          100: "rgb(var(--color-warning-100)/<alpha-value>)",
          200: "rgb(var(--color-warning-200)/<alpha-value>)",
          300: "rgb(var(--color-warning-300)/<alpha-value>)",
          400: "rgb(var(--color-warning-400)/<alpha-value>)",
          500: "rgb(var(--color-warning-500)/<alpha-value>)",
          600: "rgb(var(--color-warning-600)/<alpha-value>)",
          700: "rgb(var(--color-warning-700)/<alpha-value>)",
          800: "rgb(var(--color-warning-800)/<alpha-value>)",
          900: "rgb(var(--color-warning-900)/<alpha-value>)",
          950: "rgb(var(--color-warning-950)/<alpha-value>)",
        },
        info: {
          0: "rgb(var(--color-info-0)/<alpha-value>)",
          50: "rgb(var(--color-info-50)/<alpha-value>)",
          100: "rgb(var(--color-info-100)/<alpha-value>)",
          200: "rgb(var(--color-info-200)/<alpha-value>)",
          300: "rgb(var(--color-info-300)/<alpha-value>)",
          400: "rgb(var(--color-info-400)/<alpha-value>)",
          500: "rgb(var(--color-info-500)/<alpha-value>)",
          600: "rgb(var(--color-info-600)/<alpha-value>)",
          700: "rgb(var(--color-info-700)/<alpha-value>)",
          800: "rgb(var(--color-info-800)/<alpha-value>)",
          900: "rgb(var(--color-info-900)/<alpha-value>)",
          950: "rgb(var(--color-info-950)/<alpha-value>)",
        },
        typography: {
          0: "rgb(var(--color-typography-0)/<alpha-value>)",
          50: "rgb(var(--color-typography-50)/<alpha-value>)",
          100: "rgb(var(--color-typography-100)/<alpha-value>)",
          200: "rgb(var(--color-typography-200)/<alpha-value>)",
          300: "rgb(var(--color-typography-300)/<alpha-value>)",
          400: "rgb(var(--color-typography-400)/<alpha-value>)",
          500: "rgb(var(--color-typography-500)/<alpha-value>)",
          600: "rgb(var(--color-typography-600)/<alpha-value>)",
          700: "rgb(var(--color-typography-700)/<alpha-value>)",
          800: "rgb(var(--color-typography-800)/<alpha-value>)",
          900: "rgb(var(--color-typography-900)/<alpha-value>)",
          950: "rgb(var(--color-typography-950)/<alpha-value>)",
          white: "#FFFFFF",
          gray: "#D4D4D4",
          black: "#181718",
          primary: "rgb(var(--color-text-primary)/<alpha-value>)",
          primary_light: "rgb(var(--color-text-primary-light)/<alpha-value>)",
        },
        outline: {
          0: "rgb(var(--color-outline-0)/<alpha-value>)",
          50: "rgb(var(--color-outline-50)/<alpha-value>)",
          100: "rgb(var(--color-outline-100)/<alpha-value>)",
          200: "rgb(var(--color-outline-200)/<alpha-value>)",
          300: "rgb(var(--color-outline-300)/<alpha-value>)",
          400: "rgb(var(--color-outline-400)/<alpha-value>)",
          500: "rgb(var(--color-outline-500)/<alpha-value>)",
          600: "rgb(var(--color-outline-600)/<alpha-value>)",
          700: "rgb(var(--color-outline-700)/<alpha-value>)",
          800: "rgb(var(--color-outline-800)/<alpha-value>)",
          900: "rgb(var(--color-outline-900)/<alpha-value>)",
          950: "rgb(var(--color-outline-950)/<alpha-value>)",
        },
        background: {
          0: "rgb(var(--color-background-0)/<alpha-value>)",
          50: "rgb(var(--color-background-50)/<alpha-value>)",
          100: "rgb(var(--color-background-100)/<alpha-value>)",
          200: "rgb(var(--color-background-200)/<alpha-value>)",
          300: "rgb(var(--color-background-300)/<alpha-value>)",
          400: "rgb(var(--color-background-400)/<alpha-value>)",
          500: "rgb(var(--color-background-500)/<alpha-value>)",
          600: "rgb(var(--color-background-600)/<alpha-value>)",
          700: "rgb(var(--color-background-700)/<alpha-value>)",
          800: "rgb(var(--color-background-800)/<alpha-value>)",
          900: "rgb(var(--color-background-900)/<alpha-value>)",
          950: "rgb(var(--color-background-950)/<alpha-value>)",
          error: "rgb(var(--color-background-error)/<alpha-value>)",
          warning: "rgb(var(--color-background-warning)/<alpha-value>)",
          muted: "rgb(var(--color-background-muted)/<alpha-value>)",
          success: "rgb(var(--color-background-success)/<alpha-value>)",
          info: "rgb(var(--color-background-info)/<alpha-value>)",
          light: "#FBFBFB",
          dark: "#181719",
          primary: "rgb(var(--color-background-primary)/<alpha-value>)",
          secondary: "rgb(var(--color-background-secondary)/<alpha-value>)",
        },
        indicator: {
          primary: "rgb(var(--color-indicator-primary)/<alpha-value>)",
          info: "rgb(var(--color-indicator-info)/<alpha-value>)",
          error: "rgb(var(--color-indicator-error)/<alpha-value>)",
        },
      },
      fontFamily: {
        heading: "Poppins_600SemiBold",
        body: "Poppins_400Regular",
        mono: "Poppins_300Light",
        h1: "Poppins_700Bold",
        h2: "Poppins_600SemiBold",
        h3: "Poppins_600SemiBold",
        h4: "Poppins_600SemiBold",
        light: "Poppins_300Light",
        light_italic: "Poppins_300Light_Italic",
        roboto: ["Roboto", "sans-serif"],
      },
      fontWeight: {
        extrablack: "950",
      },
      fontSize: {
        "2xs": "10px",
        h1: ["var(--fs-3xl)", { lineHeight: "var(--lh-3xl)" }],
        h2: ["var(--fs-2xl)", { lineHeight: "var(--lh-2xl)" }],
        h3: ["var(--fs-xl)", { lineHeight: "var(--lh-xl)" }],
        h4:  ["var(--fs-base)", { lineHeight: "var(--lh-base)" }],
        subtitle0: ["var(--fs-lg)", { lineHeight: "var(--lh-lg)" }],
        subtitle1: ["var(--fs-base)", { lineHeight: "var(--lh-base)" }],
        subtitle2: ["var(--fs-sm)", { lineHeight: "var(--lh-sm)" }],
        subtitle3: ["var(--fs-xs)", { lineHeight: "var(--lh-xs)" }],
        xs: ["var(--fs-xs)", { lineHeight: "var(--lh-xs)" }],
        sm: ["var(--fs-sm)", { lineHeight: "var(--lh-sm)" }],
        base: ["var(--fs-base)", { lineHeight: "var(--lh-base)" }],
        lg: ["var(--fs-lg)", { lineHeight: "var(--lh-lg)" }],
        xl: ["var(--fs-xl)", { lineHeight: "var(--lh-xl)" }],
        "2xl": ["var(--fs-2xl)", { lineHeight: "var(--lh-2xl)" }],
        "3xl": ["var(--fs-3xl)", { lineHeight: "var(--lh-3xl)" }],
        "4xl": ["var(--fs-4xl)", { lineHeight: "var(--lh-4xl)" }],
        "5xl": ["var(--fs-5xl)", { lineHeight: "var(--lh-5xl)" }],
        "6xl": ["var(--fs-6xl)", { lineHeight: "var(--lh-6xl)" }],
      },
      boxShadow: {
        "hard-1": "-2px 2px 8px 0px rgba(38, 38, 38, 0.20)",
        "hard-2": "0px 3px 10px 0px rgba(38, 38, 38, 0.20)",
        "hard-3": "2px 2px 8px 0px rgba(38, 38, 38, 0.20)",
        "hard-4": "0px -3px 10px 0px rgba(38, 38, 38, 0.20)",
        "hard-5": "0px 2px 10px 0px rgba(38, 38, 38, 0.10)",
        "soft-1": "0px 0px 10px rgba(38, 38, 38, 0.1)",
        "soft-2": "0px 0px 20px rgba(38, 38, 38, 0.2)",
        "soft-3": "0px 0px 30px rgba(38, 38, 38, 0.1)",
        "soft-4": "0px 0px 40px rgba(38, 38, 38, 0.1)",
      },
    },
  },
  plugins: [gluestackPlugin],
};
