name: Unit Tests

on:
  # Exécuter sur tous les commits de toutes les branches
  push:
    branches: '*'
  
  # Exécuter uniquement sur les PR vers master et nutriped-prod
  pull_request:
    branches: 
      - master
      - nutriped-prod

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Run tests
        run: yarn test --ci --coverage

